### ISSUE TITLE
style(enhancement): Add problem's ID

### ISSUE THREAD

**Issue by ahr9n** [MohamedSamehMohamed/WebScrapping#5]
I think adding problem's ID before name, instead of its order would be a way better to identify the problem.
Example: '106B - Choosing Laptop.cpp' instead of 'B - Choosing Laptop.cpp'.

Notice that for parallel Div. 1 and Div. 2 contests, there are combined/merged problems (mostly CDE.. and higher from Div. 2 are ABC.. in Div. 1) and their ID are related to Div. 1 not Div. 2.

Thanks for the great work! :D

**Comment by MohamedSamehMohamed** [comment]
thank you, it's a great idea, I will add it.
