### ISSUE TITLE
Adding a stop condition

### ISSUE THREAD

**Issue by HadiElnemr** [MohamedSamehMohamed/WebScrapping#7]
The script went to a point that it repeats loading a web page without doing further actions, I think it is a termination point it and would be better if handled. I believe it can be done by scraping the last page number and doing the for loop on it.

**Comment by MohamedSamehMohamed** [comment]
thank you, though  I handled it by try and catch, was thinking when I access a non-existing page will throw an exception, but after test it now, it just goes to the last page if it does not exist, Thank you again, I will fix it.
